p = "disc_v1_b.py"; s = open(p, encoding="utf-8").read()
def rep(old, new, n=1):
    global s
    assert s.count(old) == n, (s.count(old), old[:90])
    s = s.replace(old, new)

# ===== E(c)（1）：薄殼 == 上次產物？移到拿鎖重驗之後、改第一行之前（v2.8 §3）=====
rep('b = F.band("uE2", "E(c)（1）upgrade vendor_kit[@<tag>]（單段救援路徑）：啟動器 grep 第一行 → inspect → 無才 pull → 拿鎖、重驗 → @舊版無法無損讀 → 3 → 查 registry（@<tag>／frozen 不查）→ 有新版 → 改第一行 → 用新引擎再跑；否則見「E(c)（2）」頁", v2=True)',
    'b = F.band("uE2", "E(c)（1）upgrade vendor_kit[@<tag>]（單段救援路徑）：啟動器 grep 第一行 → inspect → 無才 pull → 拿鎖、重驗 → 薄殼 == 上次產物？（否 → 1 零寫入，v2.8 §3）→ @舊版無法無損讀 → 3 → 查 registry（@<tag>／frozen 不查）→ 有新版 → 改第一行 → 用新引擎再跑；否則見「E(c)（2）」頁", v2=True)')
rep('''b.box("s12dx", U, 6, v2(O12), fl("是 → 3：印 6-10「目標引擎無法無損讀取現有檔；未修改任何檔；要退回請 git revert」（零寫入）"), 220)
b.box("s12d", E, 6, v2(D12), fl("@<tag> 為舊版且無法無損讀現有檔（P／schema）？"), 260, ax="l")
b.box("s12t", E, 7, v2(D12), fl("否 → @<tag> 指定或 CI 為真（frozen）？"), 260, ax="l")
b.box("s12tn", E, 7, v2(W12), fl("是：不查 registry"), 100, ax="r")
b.box("s12u", E, 8, v2(SUB), fl("否：查 registry（GHCR）取引擎最新正式版"), 260, ax="l")
b.box("s12v", E, 9, v2(D12), "有新版？", 200, ax="l")
b.box("s12vz", E, 9, LBL, "否／不查 → 續「E(c)（2）」頁：薄殼比對與重產", 110, ax="r", minh=40)
b.box("s12hz", U, 10, v2(G12), fl("→ 用新引擎從本頁「docker run 該引擎」格再跑一次（同一次指令內；第二次第一行又變 → 1 印 6-2b）"), 220)
b.box("s12h", L, 10, v2(W12), fl("啟動器：apply 前後 grep 第一行 → 變了 → 用新引擎再跑 upgrade vendor_kit（接手邏輯同「E(a)(b)」頁）"), 300)
b.box("s12w", E, 10, v2(SUB), fl("是：改 version.toml 第一行 = 新引擎 ref（其餘不動）"), 260, ax="l")
b.box("s12wf", P, 10, F12, "version.toml 第一行 = 新引擎 ref（進 git）", 360)''',
'''b.box("s12sx", U, 6, v2(O12), fl("否 → 1：偵測到薄殼被修改，列差異不動（零寫入；git checkout 還原後再跑）"), 220)
b.box("s12s", E, 6, v2(D12), "薄殼 == 上次產物？（首行自描述 hash、未被改）", 260, ax="l")
b.box("s12sn", P, 6, v2(NOTE), fl("「上次產物」= 薄殼首行自描述的 sha256 與其餘內容相符（Q17）；同一判斷 install 頁也用；在拿鎖重驗之後、任何寫入（含改第一行）之前檢查，不符 → 1 列差異、零寫入（v2.8 §3）"), 360)
b.box("s12dx", U, 7, v2(O12), fl("是 → 3：印 6-10「目標引擎無法無損讀取現有檔；未修改任何檔；要退回請 git revert」（零寫入）"), 220)
b.box("s12d", E, 7, v2(D12), fl("是 → @<tag> 為舊版且無法無損讀現有檔（P／schema）？"), 260, ax="l")
b.box("s12t", E, 8, v2(D12), fl("否 → @<tag> 指定或 CI 為真（frozen）？"), 260, ax="l")
b.box("s12tn", E, 8, v2(W12), fl("是：不查 registry"), 100, ax="r")
b.box("s12u", E, 9, v2(SUB), fl("否：查 registry（GHCR）取引擎最新正式版"), 260, ax="l")
b.box("s12v", E, 10, v2(D12), "有新版？", 200, ax="l")
b.box("s12vz", E, 10, LBL, "否／不查 → 續「E(c)（2）」頁：薄殼比對與重產", 110, ax="r", minh=40)
b.box("s12hz", U, 11, v2(G12), fl("→ 用新引擎從本頁「docker run 該引擎」格再跑一次（同一次指令內；第二次第一行又變 → 1 印 6-2b）"), 220)
b.box("s12h", L, 11, v2(W12), fl("啟動器：apply 前後 grep 第一行 → 變了 → 用新引擎再跑 upgrade vendor_kit（接手邏輯同「E(a)(b)」頁）"), 300)
b.box("s12w", E, 11, v2(SUB), fl("是：改 version.toml 第一行 = 新引擎 ref（其餘不動）"), 260, ax="l")
b.box("s12wf", P, 11, F12, "version.toml 第一行 = 新引擎 ref（進 git）", 360)''')
rep('b.H("se12x", "s12b", "s12bx"); b.D("se12d", "s12b", "s12d", al=True)',
    'b.H("se12x", "s12b", "s12bx"); b.D("se12s", "s12b", "s12s", al=True); b.H("se12sx", "s12s", "s12sx", "否"); b.D("se12d", "s12s", "s12d", "是", al=True)')
rep('foot(p7bcc, "p7bcc", F.y, T7E, ALL - {"inv", "tree", "pend", "rule", "note"} | {"entry"})', 'foot(p7bcc, "p7bcc", F.y, T7E, ALL - {"inv", "tree", "pend", "rule"} | {"entry"})')

# ===== E(c)（2）：拿掉「薄殼 == 上次產物？」（已在 (1) 頁），入口文字同步 =====
rep('b = F.band("uE3", "E(c)（2）薄殼比對與重產（承「E(c)（1）」頁：無新版或不查，第一行未變）：薄殼 == 上次產物？→ 否 → 1 列差異；是 → 已是本引擎產物？→ 是 → 0 無變更；否 → 建日誌 → 重產薄殼四檔 + gen/.stamp + tools.just → 刪日誌 → 1", v2=True)',
    'b = F.band("uE3", "E(c)（2）薄殼比對與重產（承「E(c)（1）」頁：無新版或不查，第一行未變；薄殼 == 上次產物已在 (1) 拿鎖重驗後驗過，v2.8 §3）：已是本引擎產物？→ 是 → 0 無變更；否 → 建日誌 → 重產薄殼四檔 + gen/.stamp + tools.just → 刪日誌 → 1", v2=True)')
rep('''b.box("s12z0", E, 0, ENTRY, "來自「E(c)（1）」頁：無新版／不查（第一行未變；已拿鎖、重驗）", 360)
b.box("s12x", U, 1, v2(O12), fl("否 → 1：偵測到薄殼被修改，列差異不動（git checkout 還原後再跑）"), 220)
b.box("s12", E, 1, v2(D12), "薄殼 == 上次產物？（首行自描述 hash、未被改）", 300, ax="l")
b.box("s12n", P, 1, v2(NOTE), fl("「上次產物」= 薄殼首行自描述的 sha256 與其餘內容相符（Q17）；同一判斷 install 頁也用；「薄殼相符」= 首行 engine 已是本引擎且 gen/.stamp 相符 → 0 無變更（v2.7 §5）"), 360)
b.box("s12z", U, 2, v2(G12), "是 → 0：無變更（薄殼相符，已是本引擎產物）", 220)
b.box("s12e", E, 2, v2(D12), fl("是 → 首行 engine == 本引擎且 gen/.stamp 相符？"), 300, ax="l")
b.box("s12l", E, 3, v2(SUB), "否：建進度日誌（第一個寫入前）", 360)
b.box("s13", E, 4, v2(SUB), "重產薄殼四檔（暫存 → 原子替換）", 360)
b.files("s13f", P, 4, "薄殼四檔（進 git）", [".vendor_kit/.gitignore", ".vendor_kit/entry.just", ".vendor_kit/vendor.just", ".vendor_kit/ci/check.sh"], 360)
b.box("s13b", E, 5, v2(SUB), "寫 gen/.stamp（本引擎 ref）", 360)
b.box("s13bf", P, 5, F12, "gen/.stamp（不進 git）", 360)
b.box("s13c", E, 6, v2(SUB), "重生 gen/tools.just（用本引擎的規則；mod? 行）", 360)
b.box("s13cf", P, 6, F12, "gen/tools.just（不進 git；mod? 行）", 360)
b.box("s13x", U, 7, v2(O12), fl("失敗 → 1：「引擎版本已鎖定為 vY，但薄殼尚未重產；請排除上述錯誤後執行：just vendor_kit upgrade vendor_kit」"), 220)
b.box("s13d", E, 7, v2(SUB), "刪進度日誌（最後一步）", 360)
b.box("s14", U, 8, v2(O12), fl("1：印「已升級引擎 vX → vY 並重產薄殼，請 commit .vendor_kit/ 並再跑原指令」"), 220)
b.D("se13", "s12z0", "s12", al=True)
b.H("se14", "s12", "s12x", "否"); b.D("se15", "s12", "s12e", "是", al=True); b.H("se15z", "s12e", "s12z", "是"); b.D("se15l", "s12e", "s12l", "否", al=True)''',
'''b.box("s12z0", E, 0, ENTRY, "來自「E(c)（1）」頁：無新版／不查（第一行未變；已拿鎖、重驗，且薄殼 == 上次產物）", 360)
b.box("s12n", P, 1, v2(NOTE), fl("「薄殼 == 上次產物」（首行自描述 sha256 與其餘內容相符，Q17）已在「E(c)（1）」頁拿鎖重驗後、任何寫入前驗過（v2.8 §3）；「薄殼相符」= 首行 engine 已是本引擎且 gen/.stamp 相符 → 0 無變更（v2.7 §5）"), 360)
b.box("s12z", U, 1, v2(G12), "是 → 0：無變更（薄殼相符，已是本引擎產物）", 220)
b.box("s12e", E, 1, v2(D12), fl("首行 engine == 本引擎且 gen/.stamp 相符？"), 300, ax="l")
b.box("s12l", E, 2, v2(SUB), "否：建進度日誌（第一個寫入前）", 360)
b.box("s13", E, 3, v2(SUB), "重產薄殼四檔（暫存 → 原子替換）", 360)
b.files("s13f", P, 3, "薄殼四檔（進 git）", [".vendor_kit/.gitignore", ".vendor_kit/entry.just", ".vendor_kit/vendor.just", ".vendor_kit/ci/check.sh"], 360)
b.box("s13b", E, 4, v2(SUB), "寫 gen/.stamp（本引擎 ref）", 360)
b.box("s13bf", P, 4, F12, "gen/.stamp（不進 git）", 360)
b.box("s13c", E, 5, v2(SUB), "重生 gen/tools.just（用本引擎的規則；mod? 行）", 360)
b.box("s13cf", P, 5, F12, "gen/tools.just（不進 git；mod? 行）", 360)
b.box("s13x", U, 6, v2(O12), fl("失敗 → 1：「引擎版本已鎖定為 vY，但薄殼尚未重產；請排除上述錯誤後執行：just vendor_kit upgrade vendor_kit」"), 220)
b.box("s13d", E, 6, v2(SUB), "刪進度日誌（最後一步）", 360)
b.box("s14", U, 7, v2(O12), fl("1：印「已升級引擎 vX → vY 並重產薄殼，請 commit .vendor_kit/ 並再跑原指令」"), 220)
b.D("se13", "s12z0", "s12e", al=True)
b.H("se15z", "s12e", "s12z", "是"); b.D("se15l", "s12e", "s12l", "否", al=True)''')

# ===== bootstrap（1）：--local 三分支（v2.8 §4）=====
rep('''b.box("a8l", L, 7, v2(W12), "是：docker load <tar>", 200, ax="l")
b.box("a6q", L, 7, v2(D12), "本機有？", 160, ax=280)
b.box("a8i", L, 8, v2(W12), fl("docker image inspect 取 image ID（否：值 = 本機 image tag）"), 200, ax="l")
b.box("a6p", L, 8, v2(W12), "無：docker pull <引擎 ref>", 200, ax="r")
b.box("a7", G, 8, IMG, "ghcr.io/…/vendor_kit:vN\\n（引擎 image；多架構 amd64+arm64）", 180)
b.box("a8d", L, 9, v2(W12), fl("讀同名 .digest 旁檔 = 正式 index digest（旁檔缺 → 1）"), 200, ax="l")
b.box("a9", L, 10, v2(W12), fl("docker run <引擎> install（-y 轉發；本機 image 直接 run）"), 300)
b.box("a9e", E, 10, SUB, fl("install（見「install（1）（2）」頁）：建／重寫 .vendor_kit/ 薄殼、根 justfile、根 .dockerignore"), 260)
b.files("a9f", P, 10, "install 寫（見「install（1）（2）」頁）", [".vendor_kit/ 薄殼四檔（首行自描述）", "version.toml 第一行（引擎 ref）", "gen/.stamp（引擎 ref）", "baseline/.gitkeep", "根 justfile（無 → import 行 + default recipe；有 → 加 import 一行）", "根 .dockerignore 三行（有 → 問後加）"], 360)
b.box("a9x", U, 11, v2(R12), "是 → 1：中止（第一次不留半成品；--local 檔未寫）", 220)
b.box("a9q", L, 11, D12, "install 失敗？", 200)
b.box("a9z", L, 12, LBL, "否 ↓ 續「bootstrap.sh（2）」頁：--local 記錄 → 對每個 -t 呼叫 add → 彙總", 460, 24, minh=24)''',
'''b.box("a8ex", U, 7, v2(O12), "否 → 1：--local 指定的檔案不存在（請檢查路徑）", 220)
b.box("a8e", L, 7, v2(D12), "是：該檔案存在？", 200, ax="l")
b.box("a6q", L, 7, v2(D12), "本機有？", 160, ax=280)
b.box("a8tx", U, 8, v2(O12), fl("是 → 1：印 6-37（值既是既存檔案也可解讀為本機 image tag，請消歧）"), 220)
b.box("a8t", L, 8, v2(D12), fl("是：本機也有同名 image tag（兩者皆成立）？"), 200, ax="l")
b.box("a6p", L, 8, v2(W12), "無：docker pull <引擎 ref>", 200, ax="r")
b.box("a7", G, 8, IMG, "ghcr.io/…/vendor_kit:vN\\n（引擎 image；多架構 amd64+arm64）", 180)
b.box("a8l", L, 9, v2(W12), "否：docker load <tar>", 200, ax="l")
b.box("a8i", L, 10, v2(W12), fl("docker image inspect 取 image ID（否：值 = 本機 image tag）"), 200, ax="l")
b.box("a8d", L, 11, v2(W12), fl("讀同名 .digest 旁檔 = 正式 index digest（旁檔缺 → 1）"), 200, ax="l")
b.box("a9", L, 12, v2(W12), fl("docker run <引擎> install（-y 轉發；本機 image 直接 run）"), 300)
b.box("a9e", E, 12, SUB, fl("install（見「install（1）（2）」頁）：建／重寫 .vendor_kit/ 薄殼、根 justfile、根 .dockerignore"), 260)
b.files("a9f", P, 12, "install 寫（見「install（1）（2）」頁）", [".vendor_kit/ 薄殼四檔（首行自描述）", "version.toml 第一行（引擎 ref）", "gen/.stamp（引擎 ref）", "baseline/.gitkeep", "根 justfile（無 → import 行 + default recipe；有 → 加 import 一行）", "根 .dockerignore 三行（有 → 問後加）"], 360, cols=2)
b.box("a9x", U, 13, v2(R12), "是 → 1：中止（第一次不留半成品；--local 檔未寫）", 220)
b.box("a9q", L, 13, D12, "install 失敗？", 200)
b.box("a9z", L, 14, LBL, "否 ↓ 續「bootstrap.sh（2）」頁：--local 記錄 → 對每個 -t 呼叫 add → 彙總", 460, 24, minh=24)''')
rep('''b.D("ae8", "a8q", "a8l", "是", al=True); b.R("ae8n", "a8q", "a8i", "否", busx=494, tx=0.75, vert=True)
b.D("ae9", "a8l", "a8i", al=True); b.D("ae9d", "a8i", "a8d", al=True)''',
'''b.D("ae8", "a8q", "a8e", "是", al=True); b.R("ae8n", "a8q", "a8i", "否", busx=494, tx=0.75, vert=True)
b.H("ae8e", "a8e", "a8ex", "否"); b.D("ae8ey", "a8e", "a8t", "是", al=True); b.H("ae8t", "a8t", "a8tx", "是"); b.D("ae8tn", "a8t", "a8l", "否", al=True)
b.D("ae9", "a8l", "a8i", al=True); b.D("ae9d", "a8i", "a8d", al=True)''')
rep('b = F.band("bA", "5a bootstrap.sh 前半：檢查 git／just → 決定引擎 ref（Q18：已有 version.toml → 用該行引擎，不退回內嵌）→ --local 走 docker load，否則 inspect → 無才 pull → 呼叫 install（失敗即中止）；後半見「bootstrap.sh（2）」頁", v2=True)',
    'b = F.band("bA", "5a bootstrap.sh 前半：檢查 git／just → 決定引擎 ref（Q18：已有 version.toml → 用該行引擎，不退回內嵌）→ --local 三分支（檔案：先驗存在 → 既是檔又是 tag → 1 + 6-37 → docker load；否則 tag，v2.8 §4），否則 inspect → 無才 pull → 呼叫 install（失敗即中止）；後半見「bootstrap.sh（2）」頁", v2=True)')

# ===== install（1）：第一次不建日誌、修復型建 .tmp.install.<id>.toml（v2.8 §2）=====
rep('b.box("i4e", E, 8, v2(D12), "薄殼已存在？", 200, ax="l")', 'b.box("i4e", E, 8, v2(D12), "薄殼已存在？", 240, ax="l")')
rep('b.box("i4q", E, 9, v2(D12), "薄殼 == 上次產物？（首行自描述 hash）", 300, ax="l")', 'b.box("i4q", E, 9, v2(D12), "薄殼 == 上次產物？（首行自描述 hash）", 240, ax="l")')
rep('''b.box("i4b", E, 10, v2(SUB), fl("是：薄殼四檔逐檔原子替換（暫存 → 正式位置）"), 400)
b.files("i4f", P, 10, "＋薄殼四檔（進 git）", [".vendor_kit/.gitignore", ".vendor_kit/entry.just", ".vendor_kit/vendor.just", ".vendor_kit/ci/check.sh"], 360)
b.box("i4c", E, 11, v2(SUB), fl("寫 version.toml：第一行 = 引擎 ref（＋schema、written_by；已有則不動）"), 400)
b.box("i4cf", P, 11, F12, "＋version.toml（第一行引擎 ref、schema、written_by；進 git）", 360)
b.box("i4d", E, 12, v2(SUB), "寫 gen/.stamp（只記引擎 ref）", 400)
b.box("i4df", P, 12, F12, "＋gen/.stamp（不進 git）", 360)
b.box("i4g", E, 13, v2(SUB), fl("建 baseline/.gitkeep（git 不追蹤空目錄；metadata 到 add 才建）"), 400)
b.box("i4gf", P, 13, F12, "＋baseline/.gitkeep（進 git）", 360)
b.box("i5z", E, 14, LBL, "↓ 續「install（2）」頁：根 justfile 與根 .dockerignore", 300, 24, ax="l", minh=24)''',
'''b.box("i4ld", E, 10, v2(D12), "第一次 install（薄殼原本不存在）？", 240, ax="l")
b.box("i4l", E, 10, v2(W12), fl("否（修復型）：建進度日誌 .tmp.install.<id>.toml"), 130, ax="r")
b.box("i4lf", P, 10, v2(F12), "＋.vendor_kit/.tmp.install.<id>.toml（進度日誌，不進 git；修復型才有，收尾後刪；第一次 install 不建，失敗整包丟棄）", 360)
b.box("i4b", E, 11, v2(SUB), fl("是：薄殼四檔逐檔原子替換（暫存 → 正式位置）"), 400)
b.files("i4f", P, 11, "＋薄殼四檔（進 git）", [".vendor_kit/.gitignore", ".vendor_kit/entry.just", ".vendor_kit/vendor.just", ".vendor_kit/ci/check.sh"], 360)
b.box("i4c", E, 12, v2(SUB), fl("寫 version.toml：第一行 = 引擎 ref（＋schema、written_by；已有則不動）"), 400)
b.box("i4cf", P, 12, F12, "＋version.toml（第一行引擎 ref、schema、written_by；進 git）", 360)
b.box("i4d", E, 13, v2(SUB), "寫 gen/.stamp（只記引擎 ref）", 400)
b.box("i4df", P, 13, F12, "＋gen/.stamp（不進 git）", 360)
b.box("i4g", E, 14, v2(SUB), fl("建 baseline/.gitkeep（git 不追蹤空目錄；metadata 到 add 才建）"), 400)
b.box("i4gf", P, 14, F12, "＋baseline/.gitkeep（進 git）", 360)
b.box("i5z", E, 15, LBL, "↓ 續「install（2）」頁：根 justfile 與根 .dockerignore", 300, 24, ax="l", minh=24)''')
rep('''b.D("ie6", "i4q", "i4b", "是", al=True); b.D("ie6n", "i4en", "i4b", al=True)''',
'''b.D("ie6", "i4q", "i4ld", "是", al=True); b.D("ie6n", "i4en", "i4ld", al=True)
b.H("ie6l", "i4ld", "i4l", "否"); b.H("ie6lf", "i4l", "i4lf", "寫"); b.D("ie6ly", "i4ld", "i4b", "是", al=True); b.D("ie6ln", "i4l", "i4b", al=True)''')
rep('b.box("i4n", P, 4, NOTE, fl("第一次 install：任一步失敗 → 丟棄暫存、移除已寫到正式位置的檔，專案不留任何檔 → 1（「不留半成品」只對第一次成立，v2.2 C）；修復時失敗 → 1 列已完成／未完成"), 360)',
    'b.box("i4n", P, 4, NOTE, fl("第一次 install（薄殼不存在）：不建進度日誌，任一步失敗 → 丟棄暫存、移除已寫到正式位置的檔，專案不留任何檔 → 1（「不留半成品」只對第一次成立，v2.2 C）；修復型 install：建 .vendor_kit/.tmp.install.<id>.toml 進度日誌（第一個寫入前），失敗 → 1 列已完成／未完成，收尾（install（2））後刪（v2.8 §2）"), 360)')
rep('b = F.band("bI", "5a′ install：專案層動詞（bootstrap.sh 代打，也可自己打）；再跑 = 引擎重寫薄殼（先比對首行自描述 hash）= 冪等修復；禁止巢狀（Q20）", v2=True)',
    'b = F.band("bI", "5a′ install：專案層動詞（bootstrap.sh 代打，也可自己打）；再跑 = 引擎重寫薄殼（先比對首行自描述 hash）= 冪等修復；第一次不建日誌、修復型建 .tmp.install.<id>.toml（v2.8 §2）；禁止巢狀（Q20）", v2=True)')

# ===== install（2）：i7「兩行」→「四行」；i7f 用 <pre> + 真 tab；收尾刪進度日誌（修復型）=====
rep('b.box("i7", E, 2, W12, fl("無：建 justfile（兩行，逐字見右）"), 120, ax="r")', 'b.box("i7", E, 2, W12, fl("無：建 justfile（四行，逐字見右）"), 120, ax="r")')
rep('''b.box("i7f", P, 2, v2(PRE), "＋justfile（新建，逐字；縮排是 recipe 本體）\\nimport '.vendor_kit/entry.just'\\n\\ndefault:\\n" + NB4 + "@just --list", 360)''',
    '''b.box("i7f", P, 2, v2(PRE), "＋justfile（新建，逐字四行；recipe 本體以 tab 縮排）\\nimport '.vendor_kit/entry.just'\\n\\ndefault:\\n\\t@just --list", 360)''')
rep('''b.box("igm", E, 9, v2(SUB), fl("插入的行記在 baseline/.vendor_kit.toml（lines）"), 250, ax="l")
b.box("igmf", P, 9, v2(F12), "baseline/.vendor_kit.toml（記 .dockerignore 的 append 行；進 git）", 360)
b.box("iz", U, 10, G12, "0：印建立／修改了什麼（含加的行）", 220)''',
'''b.box("igm", E, 9, v2(SUB), fl("插入的行記在 baseline/.vendor_kit.toml（lines）"), 250, ax="l")
b.box("igmf", P, 9, v2(F12), "baseline/.vendor_kit.toml（記 .dockerignore 的 append 行；進 git）", 360)
b.box("idl", E, 10, v2(SUB), fl("刪進度日誌 .tmp.install.<id>.toml（修復型才有；最後一步）"), 250, ax="l")
b.box("idlf", P, 10, v2(F12), "－.vendor_kit/.tmp.install.<id>.toml（修復型才有）", 360)
b.box("iz", U, 11, G12, "0：印建立／修改了什麼（含加的行）", 220)''')
rep('b.DL("ie25", "igm", "iz", "")', 'b.D("ie24", "igm", "idl", al=True); b.H("ie24f", "idl", "idlf", "刪"); b.DL("ie25", "idl", "iz", "")')
rep('b.box("igx", U, 7, v2(G12), fl("否 → 0：不寫 .dockerignore、印指示（含 justfile 結果）"), 220)', 'b.box("igx", U, 7, v2(G12), fl("否 → 0：不寫 .dockerignore、印指示（含 justfile 結果；修復型先刪進度日誌）"), 220)')
rep('b.box("igz", E, 7, v2(G12), fl("0：印建立了什麼（含 justfile 結果）"), 120, ax="r")', 'b.box("igz", E, 7, v2(G12), fl("0：印建立了什麼（含 justfile 結果；修復型先刪進度日誌）"), 120, ax="r")')

# ===== add（2）：逐檔迴圈「還有下一個 [[file]]？」；c20q 出口標是／否 =====
rep('''b.box("c21", E, 10, SUB, "寫 baseline/<repo>/（範本副本）", 400)
b.box("c21f", P, 10, F12, "＋baseline/<repo>/（進 git）", 360)
b.box("c21b", E, 11, v2(SUB), fl("寫 metadata：來源 ref@digest、最後合併版本（--local 另記 local_image_id）"), 400)
b.box("c21bf", P, 11, F12, "＋baseline/<repo>/.vendor_kit.toml（進 git）", 360)
b.box("c21c", E, 12, v2(SUB), fl("寫 metadata：每個 dest 的 state（managed／appended／unmanaged；新檔被拒才 declined）、declined_hash、append 行（lines）"), 400)
b.box("c21cf", P, 12, F12, ".vendor_kit.toml（[[file]] 各 dest 的 state／declined_hash／lines）", 360)
b.box("c21d", E, 13, v2(SUB), "寫 metadata：完成標記（complete）", 400)
b.box("c21df", P, 13, F12, ".vendor_kit.toml（complete = true）", 360)
b.box("c22", E, 14, v2(SUB), fl("重生 gen/tools.just（每個 <ns>.just 一行 mod?；一工具可多行）"), 400)
b.box("c22f", P, 14, F12, "gen/tools.just（不進 git；mod? 行）", 360)
b.box("c23", E, 15, v2(SUB), fl("最後寫 version.toml [tools]：<repo> = \\"…:<tag>@sha256:…\\""), 400)
b.box("c23f", P, 15, F12, "＋version.toml [tools] 行（進 git）", 360)
b.box("c23x", U, 16, v2(R12), "失敗 → 1：明列已完成／未完成", 220)
b.box("c23b", E, 16, v2(SUB), "刪進度日誌（最後一步）", 400)
b.box("c24", U, 17, G12, "成功 → 0：印摘要，提示 git add", 220)''',
'''b.box("c20l", E, 10, v2(D12), "還有下一個 [[file]]？", 300, ax=50)
b.box("c21", E, 11, SUB, "否：寫 baseline/<repo>/（範本副本）", 400)
b.box("c21f", P, 11, F12, "＋baseline/<repo>/（進 git）", 360)
b.box("c21b", E, 12, v2(SUB), fl("寫 metadata：來源 ref@digest、最後合併版本（--local 另記 local_image_id）"), 400)
b.box("c21bf", P, 12, F12, "＋baseline/<repo>/.vendor_kit.toml（進 git）", 360)
b.box("c21c", E, 13, v2(SUB), fl("寫 metadata：每個 dest 的 state（managed／appended／unmanaged；新檔被拒才 declined）、declined_hash、append 行（lines）"), 400)
b.box("c21cf", P, 13, F12, ".vendor_kit.toml（[[file]] 各 dest 的 state／declined_hash／lines）", 360)
b.box("c21d", E, 14, v2(SUB), "寫 metadata：完成標記（complete）", 400)
b.box("c21df", P, 14, F12, ".vendor_kit.toml（complete = true）", 360)
b.box("c22", E, 15, v2(SUB), fl("重生 gen/tools.just（每個 <ns>.just 一行 mod?；一工具可多行）"), 400)
b.box("c22f", P, 15, F12, "gen/tools.just（不進 git；mod? 行）", 360)
b.box("c23", E, 16, v2(SUB), fl("最後寫 version.toml [tools]：<repo> = \\"…:<tag>@sha256:…\\""), 400)
b.box("c23f", P, 16, F12, "＋version.toml [tools] 行（進 git）", 360)
b.box("c23x", U, 17, v2(R12), "失敗 → 1：明列已完成／未完成", 220)
b.box("c23b", E, 17, v2(SUB), "刪進度日誌（最後一步）", 400)
b.box("c24", U, 18, G12, "成功 → 0：印摘要，提示 git add", 220)''')
rep('''b.D("ce28n", "c20q", "c20n", "", 0.25, 0.5, al=True); b.D("ce28y", "c20q", "c20", "", 0.8, 0.5, al=True)
b.R("ce29", "c17", "c21", "", busx=990, tx=0.9); b.R("ce30", "c19", "c21", "", busx=990, tx=0.9); b.D("ce31", "c20", "c21", al=True); b.D("ce31n", "c20n", "c21", al=True)''',
'''b.D("ce28n", "c20q", "c20n", "否", 0.25, 0.5, al=True); b.D("ce28y", "c20q", "c20", "是", 0.8, 0.5, al=True)
b.R("ce29", "c17", "c20l", "", busx=990, tx=0.5); b.R("ce30", "c19", "c20l", "", busx=990, tx=0.5); b.D("ce31", "c20", "c20l", al=True); b.D("ce31n", "c20n", "c20l", al=True)
b.LL("ce31y", "c20l", "c16", "是", busx=565); b.D("ce31l", "c20l", "c21", "否", al=True)''')
rep('b = F.band("bB2", "5b″ add <repo> 的 apply 寫入段（承「add（1′）」頁：已拿鎖、重驗、檢查通過、非 dry-run）：建日誌 → materialize → 印記 → 初始檔逐檔 → baseline → metadata → tools.just → version.toml → 刪日誌", v2=True)',
    'b = F.band("bB2", "5b″ add <repo> 的 apply 寫入段（承「add（1′）」頁：已拿鎖、重驗、檢查通過、非 dry-run）：建日誌 → materialize → 印記 → 初始檔逐檔（每個 [[file]] 迴圈）→ baseline → metadata → tools.just → version.toml → 刪日誌", v2=True)')
open(p, "w", encoding="utf-8").write(s); print("ok")
