p = "disc_v1_b.py"; s = open(p, encoding="utf-8").read()
def rep(old, new, n=1):
    global s
    assert s.count(old) == n, (s.count(old), old[:90])
    s = s.replace(old, new)
start = s.index('# ================= P8bcc：uninstall（2）寫入段'); end = s.index('foot(p8bcc,')
new = '''# ================= P8bcc：uninstall（2）寫入段 =================
p8bcc, F = newpage("流程 v2：uninstall（2）apply 寫入段（§2；v2.2 E、v2.3 §6、v2.5 §3／§10、v2.6 Q22 補、v2.8 §1）", N8B, COLS5)
b = F.band("vD2", "uninstall（2）寫入段（承「uninstall（1）」頁：已拿鎖、重驗、非 dry-run）：建日誌 → 逐工具 remove（保護模式）→ 只刪 hash 相符的自產檔（含 baseline/ 根檔，再刪空的 baseline/；v2.8 §1）→ 根 justfile 那行、.dockerignore 三行問後刪 → 刪日誌 → 目錄空才 rmdir；不 rm -rf", v2=True)
b.box("x4e", E, 0, ENTRY, "來自「uninstall（1）」頁：apply 檢查通過（非 dry-run）", 300)
b.box("x4l", E, 1, v2(SUB), "建進度日誌（.vendor_kit/.tmp.uninstall.<id>.toml；第一個寫入前）", 400)
b.box("x4lf", P, 1, F12, "＋.vendor_kit/.tmp.uninstall.<id>.toml（進度日誌，不進 git）", 360)
b.box("x4x", U, 2, v2(R12), "任一失敗 → 1 中止，列出已完成部分", 220)
b.box("x4", E, 2, v2(SUB), fl("逐工具 remove（保護模式；步驟同「remove（2）」頁）"), 400)
b.box("x5a", E, 3, v2(SUB), "全部成功：刪薄殼四檔（hash 相符者）", 400)
b.files("x5af", P, 3, "－薄殼四檔（保護清單內的保留）", [".vendor_kit/.gitignore", ".vendor_kit/entry.just", ".vendor_kit/vendor.just", ".vendor_kit/ci/check.sh"], 360, cols=2)
b.box("x5b", E, 4, v2(SUB), "刪 version.toml（hash 相符者）", 400)
b.box("x5bf", P, 4, F12, "－version.toml（進 git）", 360)
b.box("x5c", E, 5, v2(SUB), "刪 version.local.toml（有的話；hash 相符者）", 400)
b.box("x5cf", P, 5, F12, "－version.local.toml（不進 git）", 360)
b.box("x5d", E, 6, v2(SUB), fl("刪 gen/ 與 baseline/ 內剩下的自產檔（hash 相符者；v2.8 §1）"), 400)
b.files("x5df", P, 6, "－gen/（不進 git）、baseline/ 根檔（進 git）", ["gen/.stamp", "gen/tools.just", "baseline/.gitkeep", "baseline/.vendor_kit.toml（記根 .dockerignore 的 append 行）"], 360, cols=2)
b.box("x5dd", E, 7, v2(SUB), fl("刪已空的子目錄 baseline/（gen/、cache/、ci/ 亦同；rmdir，不 rm -rf）"), 400)
b.box("x6", E, 8, D12, "根 justfile 有我們寫的那一行（完全相同）？", 260, ax="r")
b.box("x5r", P, 8, v2(RULE), fl("初始檔留著（永不刪，印清單）；使用者的 .gitignore／.dockerignore 只動我們 append 過且你同意的那幾行（v2.1 A、Q22 補）"), 360)
b.box("x8", E, 9, W12, fl("無／否：印指示（請自行移除 import 那行）"), 100, ax=0)
b.box("x7", E, 9, v2(D12), "有 → 問「要刪這一行嗎」同意？（-y 免問）", 260, ax="r")
b.box("x7y", E, 10, W12, "是：只刪那一行", 140, ax=200)
b.box("x7f", P, 10, F12, "justfile（少一行：import '.vendor_kit/entry.just'）", 360)
b.box("x9a", E, 11, v2(D12), "根 .dockerignore 存在？", 260, ax=120)
b.box("x9b", E, 12, v2(D12), fl("有 → 含我們加的三行（原文相同，CRLF／LF 等價）？"), 260, ax=120)
b.box("x9q", E, 13, v2(D12), fl("有 → 問「要刪這幾行嗎」同意？（-y 免問）"), 260, ax=120)
b.box("x9z", E, 14, v2(W12), fl("無／否：不動 .dockerignore"), 110, ax="l")
b.box("x9y", E, 14, v2(W12), "是：只刪原文相同的那幾行", 230, ax="r")
b.box("x9f", P, 14, v2(F12), ".dockerignore（少三行；其餘不動）", 360)
b.box("x5z", E, 15, v2(SUB), "刪進度日誌（最後一步；根 justfile 那行之後）= 交易完成", 400)
b.box("x5n", U, 16, v2(G12), "否 → 0：保留目錄與保護清單內的檔並回報；印摘要", 220)
b.box("x5q", E, 16, v2(D12), ".vendor_kit/ 已空？", 200, ax="l")
b.box("x5y", U, 17, v2(G12), "0：印摘要", 220)
b.box("x5t", E, 17, v2(SUB), "是：刪空目錄（rmdir；不 rm -rf）", 400)
b.D("xe7", "x4e", "x4l"); b.H("xe7f", "x4l", "x4lf", "寫"); b.D("xe8", "x4l", "x4")
b.H("xe9", "x4", "x4x", "失敗"); b.D("xe10", "x4", "x5a"); b.H("xe10f", "x5a", "x5af", "刪"); b.D("xe10b", "x5a", "x5b"); b.H("xe10bf", "x5b", "x5bf", "刪")
b.D("xe10c", "x5b", "x5c"); b.H("xe10cf", "x5c", "x5cf", "刪"); b.D("xe10d", "x5c", "x5d"); b.H("xe10df", "x5d", "x5df", "刪"); b.D("xe10e", "x5d", "x5dd")
b.D("xe12", "x5dd", "x6", "", 0.5, 0.5); b.LD("xe13", "x6", "x8", "無", busx=630, vert="left"); b.D("xe14", "x6", "x7", "有", al=True)
b.H("xe14n", "x7", "x8", "否"); b.D("xe14y", "x7", "x7y", "是", al=True); b.H("xe15", "x7y", "x7f", "寫")
b.D("xe16z", "x8", "x9a", al=True); b.D("xe16y", "x7y", "x9a", "", 0.5, 0.5)
b.D("xe16a", "x9a", "x9b", "有", al=True); b.D("xe16b", "x9b", "x9q", "有", al=True); b.D("xe16q", "x9q", "x9y", "是", al=True); b.H("xe16f", "x9y", "x9f", "寫")
b.LD("xe16an", "x9a", "x9z", "無", busx=635, vert="left"); b.LD("xe16bn", "x9b", "x9z", "無", busx=635, vert="left"); b.D("xe16qn", "x9q", "x9z", "否", 0.5, 0.5)
b.D("xe16v", "x9y", "x5z", al=True); b.D("xe16w", "x9z", "x5z", al=True)
b.D("xe17", "x5z", "x5q", al=True); b.H("xe18", "x5q", "x5n", "否"); b.D("xe19", "x5q", "x5t", "是", al=True); b.H("xe20", "x5t", "x5y")
b.close()
'''
s = s[:start] + new + s[end:]
rep(''' ("uninstall（v2.2 E、v2.5 §10）", "全部拆掉 = resolve（預檢全部工具、算自產檔 hash 得保護清單）→ apply（flock → 重驗 → dry-run 分支 → 建日誌 → 逐工具 remove 走保護模式 → 只刪 hash 相符的自產檔 → 根 justfile 那行問後刪 → 最後刪日誌 → 目錄空了才刪）；不 rm -rf .vendor_kit/"),''',
    ''' ("uninstall（v2.2 E、v2.5 §10、v2.8 §1）", "全部拆掉 = resolve（預檢全部工具、算自產檔 hash 得保護清單）→ apply（flock → 重驗 → dry-run 分支 → 建日誌 → 逐工具 remove 走保護模式 → 只刪 hash 相符的自產檔，含專案層 baseline/.gitkeep、baseline/.vendor_kit.toml，再刪空的 baseline/ → 根 justfile 那行問後刪 → 最後刪日誌 → 目錄空了才 rmdir）；不 rm -rf .vendor_kit/"),''')
open(p, "w", encoding="utf-8").write(s); print("ok")
