// @generated by msggen from doc/contract/reason_codes.csv; do not edit.
// Regenerate: cargo run -p msggen -- --csv doc/contract/reason_codes.csv --rust engine/messages/src/generated.rs

use crate::{Disposition, Level, Message, Source};

pub const VK0001: Message = Message {
    code: "VK0001",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Engine],
    text: "Cannot list versions for <repo>: registry read access is required; pulling still uses the host's Docker credentials. Add --registry-token-file <path> and rerun, or specify a version directly: just vendor_kit <cmd> <repo>@<tag>",
};

pub const VK0002: Message = Message {
    code: "VK0002",
    level: Level::Error,
    disposition: Some(Disposition::Pending),
    sources: &[Source::Bootstrap, Source::Engine],
    text: "Confirmation is required, but no terminal is available for interaction. No files were modified except the run log. Run from a terminal, or rerun with -y: <command_with_y>",
};

pub const VK0004: Message = Message {
    code: "VK0004",
    level: Level::Error,
    disposition: Some(Disposition::Pending),
    sources: &[Source::Engine, Source::Test],
    text: "Import of <repo> is incomplete. Run: just vendor_kit add <repo>",
};

pub const VK0005: Message = Message {
    code: "VK0005",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Bootstrap],
    text: "just 1.33.0 or later is required; the current version is <version>. Install a GitHub Release build of just 1.33.0 or later, confirm it with just --version in the current shell, and rerun bootstrap.sh.\nDownload: <download_url>",
};

pub const VK0006: Message = Message {
    code: "VK0006",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Bootstrap, Source::Engine, Source::Test],
    text: "Shell files do not match this engine version's templates: <files>. No shell files were regenerated. Review the following differences; download bootstrap.sh again from the Release, run chmod +x bootstrap.sh, then run ./bootstrap.sh --repair in the install directory.",
};

pub const VK0007: Message = Message {
    code: "VK0007",
    level: Level::Fatal,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Engine],
    text: "Target engine <vY> (interface version <P>, schema version <M>) cannot read the existing files (schema version <N>) without loss. No files were modified except the run log. Specify a version that can read schema version <N>: just vendor_kit upgrade --engine=<tag>",
};

pub const VK0008: Message = Message {
    code: "VK0008",
    level: Level::Fatal,
    disposition: Some(Disposition::Pending),
    sources: &[Source::Engine, Source::Test],
    text: "Cannot read <file>: schema version <N> is newer than the maximum supported version <M>; written by vendor_kit <written_by>. Upgrade the engine: just vendor_kit upgrade --engine",
};

pub const VK0009: Message = Message {
    code: "VK0009",
    level: Level::Fatal,
    disposition: Some(Disposition::Pending),
    sources: &[Source::Engine, Source::Launcher],
    text: "Shell interface version <P_shell> is older than required for general recipes in engine <vY>. Run first: just vendor_kit upgrade --engine",
};

pub const VK0010: Message = Message {
    code: "VK0010",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Bootstrap, Source::Engine, Source::Launcher, Source::Test],
    text: "Cannot write run log <path>: <reason>. vendor_kit does not run without a log; no files were modified. Free disk space or fix the permissions and retry.",
};

pub const VK0011: Message = Message {
    code: "VK0011",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Bootstrap, Source::Launcher],
    text: "Detected Podman (docker --version). vendor_kit supports only Docker. Switch to Docker (rootful or rootless) and retry.",
};

pub const VK0012: Message = Message {
    code: "VK0012",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Bootstrap, Source::Launcher],
    text: "Docker 19.03 or later is required; the current version is <version>. Upgrade Docker and retry.",
};

pub const VK0013: Message = Message {
    code: "VK0013",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Engine, Source::Test],
    text: "Cannot process <file>: metadata is missing or corrupt and cannot be restored reliably. vendor_kit does not guess when records are unavailable; no files of the tool that <file> belongs to were modified. Preserve <file> and run log <path>. If the metadata was committed to Git, restore it from Git and retry. Otherwise, report the issue at https://github.com/ycpss91255-research/vendor_kit/issues and attach both files.",
};

pub const VK0014: Message = Message {
    code: "VK0014",
    level: Level::Warn,
    disposition: None,
    sources: &[Source::Engine, Source::Test],
    text: "The baseline for <repo> is behind the lock version line. Run: just vendor_kit upgrade <repo> -y",
};

pub const VK0015: Message = Message {
    code: "VK0015",
    level: Level::Warn,
    disposition: None,
    sources: &[Source::Engine],
    text: "The file set or per-file digests in cache/ for <repo> did not match; refetched according to the lock version line.",
};

pub const VK0018: Message = Message {
    code: "VK0018",
    level: Level::Warn,
    disposition: None,
    sources: &[Source::Engine],
    text: "<file> already exists and is unmanaged.<effect> It was neither overwritten nor brought under management.",
};

pub const VK0019: Message = Message {
    code: "VK0019",
    level: Level::Warn,
    disposition: None,
    sources: &[Source::Engine],
    text: "<file> is unmanaged and was not processed.",
};

pub const VK0020: Message = Message {
    code: "VK0020",
    level: Level::Warn,
    disposition: None,
    sources: &[Source::Engine],
    text: "Version <tag> of <repo> was previously rejected; it was not prompted again or applied.",
};

pub const VK0021: Message = Message {
    code: "VK0021",
    level: Level::Warn,
    disposition: None,
    sources: &[Source::Engine],
    text: "<file> contains merge conflicts. Review and resolve them: git status",
};

pub const VK0023: Message = Message {
    code: "VK0023",
    level: Level::Error,
    disposition: Some(Disposition::Pending),
    sources: &[Source::Bootstrap, Source::Engine, Source::Test],
    text: "Engine <vY> is now installed. Run again: <original_command>",
};

pub const VK0024: Message = Message {
    code: "VK0024",
    level: Level::Error,
    disposition: None,
    sources: &[Source::Engine],
    text: "No command was specified.",
};

pub const VK0025: Message = Message {
    code: "VK0025",
    level: Level::Error,
    disposition: None,
    sources: &[Source::Bootstrap, Source::Engine],
    text: "Required argument is missing: <argument>.",
};

pub const VK0026: Message = Message {
    code: "VK0026",
    level: Level::Error,
    disposition: None,
    sources: &[Source::Bootstrap, Source::Engine, Source::Test],
    text: "Unknown, extra, or disallowed argument: <value>.",
};

pub const VK0027: Message = Message {
    code: "VK0027",
    level: Level::Error,
    disposition: None,
    sources: &[Source::Engine],
    text: "Invalid tag format: <tag>. Use vX.Y.Z with no leading zeros in X, Y, or Z.",
};

pub const VK0028: Message = Message {
    code: "VK0028",
    level: Level::Error,
    disposition: Some(Disposition::Pending),
    sources: &[Source::Engine, Source::Test],
    text: "The current directory is not an install directory. Run: cd <install_dir>",
};

pub const VK0029: Message = Message {
    code: "VK0029",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Bootstrap, Source::Engine],
    text: "Cannot create a nested install directory: <existing_install_dir> is already an install directory.",
};

pub const VK0030: Message = Message {
    code: "VK0030",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Engine],
    text: "Namespace <ns> for <repo> is already used by <owner>.",
};

pub const VK0031: Message = Message {
    code: "VK0031",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Bootstrap, Source::Engine],
    text: "Cannot use image <image>: <reason>. The supplied image was not used.",
};

pub const VK0032: Message = Message {
    code: "VK0032",
    level: Level::Error,
    disposition: Some(Disposition::Pending),
    sources: &[Source::Test],
    text: "Test cannot run while a local override of <target> is active. Run: <undev_command>",
};

pub const VK0033: Message = Message {
    code: "VK0033",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Bootstrap, Source::Launcher],
    text: "Docker was not found on the host. Install Docker and retry.",
};

pub const VK0034: Message = Message {
    code: "VK0034",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Bootstrap],
    text: "just was not found on the host. Install a GitHub Release build of just 1.33.0 or later, confirm it with just --version in the current shell, and rerun bootstrap.sh.\nDownload: <download_url>",
};

pub const VK0035: Message = Message {
    code: "VK0035",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Bootstrap],
    text: "Cannot find .git in the current directory or any parent directory. Run bootstrap.sh from within a Git repository.",
};

pub const VK0036: Message = Message {
    code: "VK0036",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Bootstrap, Source::Engine, Source::Launcher],
    text: "Cannot obtain engine image <image>: <reason>. No alternative engine version was used.",
};

pub const VK0037: Message = Message {
    code: "VK0037",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Bootstrap],
    text: "Cannot read exactly one valid engine lock version line from .vendor_kit/version.toml. Initial import was not attempted.",
};

pub const VK0038: Message = Message {
    code: "VK0038",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Bootstrap],
    text: "Image <image> does not exactly match the engine lock version line <locked_image>. The supplied image was not used.",
};

pub const VK0039: Message = Message {
    code: "VK0039",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Bootstrap],
    text: "Cannot repair shell files outside an install directory. Initial import was not attempted.",
};

pub const VK0040: Message = Message {
    code: "VK0040",
    level: Level::Fatal,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Bootstrap],
    text: "This bootstrap.sh is for major version <bootstrap_X>, but the locked engine requires major version <engine_X>. No files were modified. Download bootstrap.sh for major version <engine_X> from the Release and retry.",
};

pub const VK0041: Message = Message {
    code: "VK0041",
    level: Level::Error,
    disposition: Some(Disposition::Pending),
    sources: &[Source::Engine, Source::Test],
    text: "Upgrade of <repo> is incomplete. Run again: <original_command>",
};

pub const VK0042: Message = Message {
    code: "VK0042",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Engine, Source::Test],
    text: "Timed out waiting for the lock in <install_dir>. No files were modified except the run log. Wait for the other execution to finish and retry.",
};

pub const VK0043: Message = Message {
    code: "VK0043",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Engine],
    text: "Downloaded image <image> for <repo> does not match locked digest <digest>. Synchronization did not complete.",
};

pub const VK0044: Message = Message {
    code: "VK0044",
    level: Level::Warn,
    disposition: None,
    sources: &[Source::Engine],
    text: "The existing stamp for <repo> was corrupt; refetched according to the lock version line and rebuilt the stamp.",
};

pub const VK0045: Message = Message {
    code: "VK0045",
    level: Level::Error,
    disposition: Some(Disposition::Pending),
    sources: &[Source::Engine],
    text: "Cannot add <repo> at <tag>: it is already imported at <current_tag>. Run: <upgrade_command>",
};

pub const VK0046: Message = Message {
    code: "VK0046",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Engine],
    text: "Tool <repo> is not in the lock version lines. The requested operation did not complete.",
};

pub const VK0047: Message = Message {
    code: "VK0047",
    level: Level::Error,
    disposition: Some(Disposition::Pending),
    sources: &[Source::Test],
    text: "Cannot complete checks for <target>: required local files are missing: <files>. Run: just vendor_kit sync",
};

pub const VK0048: Message = Message {
    code: "VK0048",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Test],
    text: "Cannot check tool delivery content: <path> contains no delivery content.",
};

pub const VK0049: Message = Message {
    code: "VK0049",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Test],
    text: "Cannot complete checks for <target>: <reason>.",
};

pub const VK0050: Message = Message {
    code: "VK0050",
    level: Level::Error,
    disposition: Some(Disposition::Pending),
    sources: &[Source::Engine],
    text: "A different local override is already active for <target>. Run first: <undev_command>",
};

pub const VK0051: Message = Message {
    code: "VK0051",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Engine],
    text: "Cannot use local source <path> for <repo>: <reason>. The local override was not enabled.",
};

pub const VK0052: Message = Message {
    code: "VK0052",
    level: Level::Error,
    disposition: Some(Disposition::Pending),
    sources: &[Source::Engine],
    text: "Cannot read the local override source <source> for <target>: <reason>. Run: <undev_command>",
};

pub const VK0053: Message = Message {
    code: "VK0053",
    level: Level::Error,
    disposition: Some(Disposition::Pending),
    sources: &[Source::Engine, Source::Test],
    text: "The undev operation for <target> is incomplete. Run again: <undev_command>",
};

pub const VK0054: Message = Message {
    code: "VK0054",
    level: Level::Error,
    disposition: Some(Disposition::Pending),
    sources: &[Source::Bootstrap, Source::Engine, Source::Test],
    text: "Operation <operation> in <install_dir> is incomplete. Run again: <original_command>",
};

pub const VK0055: Message = Message {
    code: "VK0055",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Engine],
    text: "Cannot access <source> for <target>: <reason>. The requested operation did not complete.",
};

pub const VK0056: Message = Message {
    code: "VK0056",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Bootstrap, Source::Engine, Source::Launcher, Source::Test],
    text: "Internal vendor_kit error: <reason>. This is a VK bug. Report it at https://github.com/ycpss91255-research/vendor_kit/issues and attach run log <path>.",
};

pub const VK0057: Message = Message {
    code: "VK0057",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Engine],
    text: "Cannot add vendor_kit: vendor_kit is a reserved name. Use a different tool name.",
};

pub const VK0058: Message = Message {
    code: "VK0058",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Engine],
    text: "Cannot determine the latest version of <repo>: the registry has tags, but none is a valid vX.Y.Z tag. The query did not complete.",
};

pub const VK0059: Message = Message {
    code: "VK0059",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Engine, Source::Test],
    text: "Invalid configuration in .vendor_kit/config.toml: <field> = <value>. The requested operation did not complete. Fix <field>: <fix>.",
};

pub const VK0060: Message = Message {
    code: "VK0060",
    level: Level::Warn,
    disposition: None,
    sources: &[Source::Engine, Source::Test],
    text: "Locking is disabled in <install_dir> by lock_enabled = false in .vendor_kit/config.toml. Concurrent executions are not protected by shared or exclusive locks. Use this setting only on filesystems without file lock support; otherwise set lock_enabled = true.",
};

pub const VK0061: Message = Message {
    code: "VK0061",
    level: Level::Warn,
    disposition: None,
    sources: &[Source::Engine],
    text: "Cannot reclaim inserted lines from <file>: the recorded whole-file hash is missing or differs from the current hash, or the original text does not occur exactly once. The lines were not removed. Handle them manually.\nOriginal text: <text>\nCurrently matching line numbers: <line_numbers>.",
};

pub const VK0062: Message = Message {
    code: "VK0062",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Test],
    text: "Installation checks returned <check_exit_code>. No tests were started for <path>. Resolve the check diagnostics and retry.",
};

pub const VK0063: Message = Message {
    code: "VK0063",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Test],
    text: "Invalid test path <path>: <reason>. No tests were started. Specify one file or directory under the install directory's test/ and retry.",
};

pub const VK0064: Message = Message {
    code: "VK0064",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Test],
    text: "Cannot run <path>: VK recorded this test as delivered by tool <repo>. No tests were started. Select a scope containing only user-maintained tests that were not delivered by tools.",
};

pub const VK0065: Message = Message {
    code: "VK0065",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Test],
    text: "No tests were selected under <path>. No tests were started. Specify a path containing tests and retry.",
};

pub const VK0066: Message = Message {
    code: "VK0066",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Test],
    text: "Cannot complete the test runner for <path>: <reason>. Check the test image and command in .vendor_kit/config.toml and retry.\nRunner exit code: <runner_exit_code>.",
};

pub const VK0067: Message = Message {
    code: "VK0067",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Test],
    text: "Tests failed for <path>. Review the runner output, fix the failing tests, and retry.\nRunner exit code: <runner_exit_code>.",
};

pub const VK0068: Message = Message {
    code: "VK0068",
    level: Level::Error,
    disposition: Some(Disposition::Pending),
    sources: &[Source::Engine],
    text: "Installed tools are missing cache/ directories: <repos>. Run: just vendor_kit sync",
};

pub const VK0069: Message = Message {
    code: "VK0069",
    level: Level::Error,
    disposition: Some(Disposition::Pending),
    sources: &[Source::Engine],
    text: "Writing <file> did not complete: <reason>. Run again: <original_command>",
};

pub const VK0070: Message = Message {
    code: "VK0070",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Bootstrap, Source::Engine, Source::Launcher, Source::Test],
    text: "Version file <file> is not canonical: <reason>. The requested operation did not complete.",
};

pub const VK0071: Message = Message {
    code: "VK0071",
    level: Level::Error,
    disposition: Some(Disposition::Pending),
    sources: &[Source::Engine, Source::Test],
    text: "Local override for tool <repo> has no corresponding lock version line. The requested operation did not complete. Run: just vendor_kit undev <repo>",
};

pub const VK0072: Message = Message {
    code: "VK0072",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Engine, Source::Test],
    text: "Cannot parse .vendor_kit/config.toml: <reason>. Fix the syntax and retry.",
};

pub const VK0073: Message = Message {
    code: "VK0073",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Engine],
    text: "Cannot read <file>: <reason>. The requested operation did not complete.",
};

pub const VK0074: Message = Message {
    code: "VK0074",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Engine],
    text: "Content for <repo> at version <tag> differs from the existing stamp. The requested operation did not complete.",
};

pub const VK0075: Message = Message {
    code: "VK0075",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Engine, Source::Test],
    text: "Invalid tool delivery format for <repo>: <reason>. The requested operation did not complete.",
};

pub const VK0076: Message = Message {
    code: "VK0076",
    level: Level::Fatal,
    disposition: Some(Disposition::Pending),
    sources: &[Source::Engine, Source::Launcher],
    text: "Shell interface version <P_shell> exceeds the maximum <P_current> accepted by engine <vY>. Run: just vendor_kit upgrade --engine",
};

pub const VK0077: Message = Message {
    code: "VK0077",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Bootstrap, Source::Engine, Source::Launcher],
    text: "<operation> failed: <reason>. The requested operation did not complete.",
};

pub const VK0078: Message = Message {
    code: "VK0078",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Engine],
    text: "Tag <tag> for <repo> resolves to different digests: <digests>. The requested operation did not complete.",
};

pub const VK0079: Message = Message {
    code: "VK0079",
    level: Level::Error,
    disposition: Some(Disposition::Pending),
    sources: &[Source::Engine],
    text: "Shell files match an older engine template. Run: <upgrade_command>",
};

pub const VK0080: Message = Message {
    code: "VK0080",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Launcher],
    text: "The interface version range of engine image <image> differs from vendor_kit_protocols in version.toml. The engine was not started.",
};

pub const VK0081: Message = Message {
    code: "VK0081",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Bootstrap, Source::Launcher],
    text: "Docker daemon configuration <mode> is unsupported. Switch to supported rootful or rootless Docker and retry.",
};

pub const VK0082: Message = Message {
    code: "VK0082",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Bootstrap, Source::Launcher],
    text: "Docker capability check failed: <reason>. Fix the environment and retry.",
};

pub const VK0083: Message = Message {
    code: "VK0083",
    level: Level::Error,
    disposition: Some(Disposition::Pending),
    sources: &[Source::Bootstrap],
    text: "Uninstall is incomplete. Run: <completion_command>",
};

pub const VK0084: Message = Message {
    code: "VK0084",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Engine],
    text: "Appending to existing unmanaged file <file> requires confirmation, but interaction is unavailable and -y does not answer this prompt. Rerun just vendor_kit add <repo> from a terminal and answer the prompt there.",
};

pub const VK0085: Message = Message {
    code: "VK0085",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Engine],
    text: "Local engine image <image> accepts interface versions <P_floor> through <P_current>, excluding shell version <P_shell>. The local override was not enabled. Use an image whose range includes <P_shell>.",
};

pub const VK0086: Message = Message {
    code: "VK0086",
    level: Level::Fatal,
    disposition: Some(Disposition::Pending),
    sources: &[Source::Launcher],
    text: "Local override image <image> accepts interface versions <P_floor> through <P_current>, excluding shell version <P_shell>. Remove the override before selecting a compatible image: just vendor_kit undev --engine",
};

pub const VK0087: Message = Message {
    code: "VK0087",
    level: Level::Warn,
    disposition: None,
    sources: &[Source::Engine],
    text: "The baseline merge result for <file> is invalid (TOML that fails to parse, or a just file with conflict markers). <outcome> Manually merge the new version shipped with the version being switched to into <file>.",
};

pub const VK0088: Message = Message {
    code: "VK0088",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Engine],
    text: "The lock version line for <target> is <locked_tag>, but the latest version in the registry is the older <latest_tag>. No version change was made. To switch to <latest_tag>, run: <command>",
};

pub const VK0089: Message = Message {
    code: "VK0089",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Engine],
    text: "Tool image <image> is not a multi-architecture index (received media type <media_type>). The lock version line was not written.",
};

pub const VK0090: Message = Message {
    code: "VK0090",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Engine],
    text: "Local image <image> is not a vendor_kit engine: <reason>. The local override was not enabled. Use a valid engine image.",
};

pub const VK0091: Message = Message {
    code: "VK0091",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Engine],
    text: "<file> does not match the offline delivery format: <reason>. The lock version line was not changed.",
};

pub const VK0092: Message = Message {
    code: "VK0092",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Engine],
    text: "Cannot delete session directory <path>: <reason>. Other items were cleaned as usual.",
};

pub const VK0093: Message = Message {
    code: "VK0093",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Engine],
    text: "Cannot delete container <container>: <reason>. Other items were cleaned as usual.",
};

pub const VK0094: Message = Message {
    code: "VK0094",
    level: Level::Error,
    disposition: Some(Disposition::Failed),
    sources: &[Source::Bootstrap],
    text: "Uninstall is incomplete, but its progress file uses an old format that does not record the engine and retained-list data needed to finish, so it cannot be completed automatically. Manually finish the remaining steps according to the uninstall removal scope, then delete the uninstall progress file.",
};

/// Every active code, in ascending order.
pub const ALL: &[Message] = &[
    VK0001,
    VK0002,
    VK0004,
    VK0005,
    VK0006,
    VK0007,
    VK0008,
    VK0009,
    VK0010,
    VK0011,
    VK0012,
    VK0013,
    VK0014,
    VK0015,
    VK0018,
    VK0019,
    VK0020,
    VK0021,
    VK0023,
    VK0024,
    VK0025,
    VK0026,
    VK0027,
    VK0028,
    VK0029,
    VK0030,
    VK0031,
    VK0032,
    VK0033,
    VK0034,
    VK0035,
    VK0036,
    VK0037,
    VK0038,
    VK0039,
    VK0040,
    VK0041,
    VK0042,
    VK0043,
    VK0044,
    VK0045,
    VK0046,
    VK0047,
    VK0048,
    VK0049,
    VK0050,
    VK0051,
    VK0052,
    VK0053,
    VK0054,
    VK0055,
    VK0056,
    VK0057,
    VK0058,
    VK0059,
    VK0060,
    VK0061,
    VK0062,
    VK0063,
    VK0064,
    VK0065,
    VK0066,
    VK0067,
    VK0068,
    VK0069,
    VK0070,
    VK0071,
    VK0072,
    VK0073,
    VK0074,
    VK0075,
    VK0076,
    VK0077,
    VK0078,
    VK0079,
    VK0080,
    VK0081,
    VK0082,
    VK0083,
    VK0084,
    VK0085,
    VK0086,
    VK0087,
    VK0088,
    VK0089,
    VK0090,
    VK0091,
    VK0092,
    VK0093,
    VK0094,
];
