//! 把訊息表轉成文字；只依輸入的列，輸出逐位元組確定（ADR-0012）。

use crate::table::{Disposition, Level, Row, Source};
use std::fmt::Write as _;

const HEADER: &str = "@generated by msggen from doc/contract/reason_codes.csv; do not edit.";

/// `engine/messages/src/generated.rs` 的內容。
pub fn rust(rows: &[Row]) -> String {
    let mut out = String::new();
    out.push_str(&format!("// {HEADER}\n"));
    out.push_str("// Regenerate: cargo run -p msggen -- --csv doc/contract/reason_codes.csv --rust engine/messages/src/generated.rs\n\n");
    out.push_str("use crate::{Disposition, Level, Message, Source};\n");
    for row in sorted(rows) {
        let sources: Vec<&str> = row.sources.iter().map(|s| source_rust(*s)).collect();
        let _ = write!(
            out,
            "\npub const {code}: Message = Message {{\n    code: {code:?},\n    level: {level},\n    disposition: {disposition},\n    sources: &[{sources}],\n    text: {text:?},\n}};\n",
            code = row.code,
            level = level_rust(row.level),
            disposition = disposition_rust(row.disposition),
            sources = sources.join(", "),
            text = row.message_en,
        );
    }
    out.push_str("\n/// Every active code, in ascending order.\npub const ALL: &[Message] = &[\n");
    for row in sorted(rows) {
        let _ = writeln!(out, "    {},", row.code);
    }
    out.push_str("];\n");
    out
}

/// 主機端 bash 用的片段（`bootstrap.sh` 內嵌、啟動器 `launcher/` 載入）：只收 `source` 含 `bootstrap` 或 `launcher` 的列。
pub fn bash(rows: &[Row]) -> String {
    let mut out = String::new();
    out.push_str(&format!("# {HEADER}\n"));
    out.push_str("# Diagnostics used by bootstrap.sh and the launcher: vk_msg_<code>_level, vk_msg_<code>_exit, vk_msg_<code>_text.\n");
    for row in sorted(rows).into_iter().filter(|r| {
        r.sources
            .iter()
            .any(|s| matches!(s, Source::Bootstrap | Source::Launcher))
    }) {
        let _ = write!(
            out,
            "vk_msg_{code}_level={level}\nvk_msg_{code}_exit={exit}\nvk_msg_{code}_text={text}\n",
            code = row.code,
            level = level_word(row.level),
            exit = row.level.exit_code(),
            text = shell_quote(&row.message_en),
        );
    }
    out
}

fn sorted(rows: &[Row]) -> Vec<&Row> {
    let mut v: Vec<&Row> = rows.iter().collect();
    v.sort_by(|a, b| a.code.cmp(&b.code));
    v
}

fn level_rust(l: Level) -> &'static str {
    match l {
        Level::Warn => "Level::Warn",
        Level::Error => "Level::Error",
        Level::Fatal => "Level::Fatal",
    }
}

fn level_word(l: Level) -> &'static str {
    match l {
        Level::Warn => "warn",
        Level::Error => "error",
        Level::Fatal => "fatal",
    }
}

fn disposition_rust(d: Option<Disposition>) -> &'static str {
    match d {
        None => "None",
        Some(Disposition::Pending) => "Some(Disposition::Pending)",
        Some(Disposition::Failed) => "Some(Disposition::Failed)",
    }
}

fn source_rust(s: Source) -> &'static str {
    match s {
        Source::Bootstrap => "Source::Bootstrap",
        Source::Engine => "Source::Engine",
        Source::Launcher => "Source::Launcher",
        Source::Test => "Source::Test",
    }
}

/// POSIX shell 單引號：`'` 換成 `'\''`，換行原樣留在引號內。
fn shell_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', r"'\''"))
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    fn row(code: &str, sources: Vec<Source>, text: &str) -> Row {
        Row {
            code: code.into(),
            level: Level::Error,
            disposition: None,
            sources,
            message_en: text.into(),
        }
    }

    #[test]
    fn output_does_not_depend_on_input_order() {
        let a = row("VK0001", vec![Source::Bootstrap], "A.");
        let b = row("VK0002", vec![Source::Engine], "B.");
        let one = [a.clone(), b.clone()];
        let two = [b, a];
        assert_eq!(rust(&one), rust(&two));
        assert_eq!(bash(&one), bash(&two));
    }

    #[test]
    fn bash_keeps_only_host_rows_and_quotes() {
        let rows = [
            row("VK0001", vec![Source::Bootstrap], "It's\nfine."),
            row("VK0002", vec![Source::Engine], "Engine only."),
            row("VK0009", vec![Source::Launcher], "Launcher only."),
            row("VK0013", vec![Source::Test], "Test only."),
        ];
        let out = bash(&rows);
        assert!(out.contains("vk_msg_VK0001_text='It'\\''s\nfine.'\n"));
        assert!(out.contains("vk_msg_VK0001_exit=2\n"));
        assert!(!out.contains("VK0002"));
        assert!(out.contains("vk_msg_VK0009_text='Launcher only.'\n"));
        assert!(!out.contains("VK0013"));
    }

    #[test]
    fn rust_escapes_text() {
        let out = rust(&[row("VK0001", vec![Source::Engine], "Say \"hi\".\nNext")]);
        assert!(out.contains(r#"text: "Say \"hi\".\nNext","#));
    }
}
